import { AppShell } from "@/components/app/app-shell";
import { ProjectCard } from "@/components/projects/project-card";
const projects=[
{id:"healthcare",title:"AI Healthcare Assistant",description:"A practical assistant that helps students navigate reliable health information.",tags:["AI","Healthcare","Web"],roles:["AI/ML","Backend","UI/UX"],members:"3 / 5",match:"94%"},
{id:"campus",title:"Smart Campus Navigation",description:"A navigation experience designed around the places students actually use.",tags:["Maps","AI","Mobile"],roles:["React","Maps","Backend"],members:"2 / 4",match:"89%"},
{id:"game",title:"Game Analytics Toolkit",description:"A small analytics layer for understanding player behavior and progression.",tags:["Gaming","Data"],roles:["C#","Data","UI/UX"],members:"3 / 5",match:"86%"},
{id:"climate",title:"Campus Energy Monitor",description:"Track classroom energy use and surface practical opportunities to reduce waste.",tags:["IoT","Sustainability","Data"],roles:["IoT","Backend","Data"],members:"2 / 5",match:"82%"},
];
export default function DiscoverPage(){return <AppShell><div className="discover-page"><section className="page-intro"><div><p className="eyebrow">Discover</p><h1>Find something worth building.</h1><p className="muted-copy">Projects are ordered around your skills, interests and current availability.</p></div></section><div className="discover-toolbar"><input className="input" placeholder="Search ideas..." aria-label="Search ideas"/><button className="filter-button">Filters <span>⌄</span></button><div className="sort-tabs"><button className="active">Recommended</button><button>Newest</button><button>Most relevant</button></div></div><div className="discover-layout"><aside className="filter-panel"><strong>Filter projects</strong><label><span>Specialization</span><select className="input"><option>Any specialization</option><option>CSE</option><option>ECE</option></select></label><label><span>Interest</span><select className="input"><option>Any interest</option><option>AI</option><option>Gaming</option><option>Healthcare</option></select></label><label><span>Team size</span><select className="input"><option>Any size</option><option>2–4</option><option>3–5</option></select></label><label><span>Experience</span><select className="input"><option>Any level</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label></aside><section className="project-grid discover-grid">{projects.map(p=><ProjectCard key={p.id} project={p}/>)}</section></div></div></AppShell>}
