import Link from "next/link";
import { AppShell } from "@/components/app/app-shell";
import { Button } from "@/components/ui/button";

const projects = [
  { title: "AI Healthcare Assistant", tags: "AI · Healthcare · Web", roles: "AI/ML · Backend · UI/UX", members: "3 / 5", match: "94%", description: "A practical assistant that helps students navigate reliable health information." },
  { title: "Smart Campus Navigation", tags: "Maps · AI · Mobile", roles: "React · Maps · Backend", members: "2 / 4", match: "89%", description: "A navigation experience designed around the places students actually use." },
  { title: "Game Analytics Toolkit", tags: "Gaming · Data", roles: "C# · Data · UI/UX", members: "3 / 5", match: "86%", description: "A small analytics layer for understanding player behavior and progression." },
];

export default function DashboardPage() {
  return <AppShell><div className="dashboard"><section className="page-intro"><div><p className="eyebrow">Your workspace</p><h1>Good morning.</h1><p className="muted-copy">Find something worth building, or turn your own idea into a squad.</p></div><div className="intro-actions"><Button href="/onboarding">+ Update profile</Button><Button variant="secondary" href="#ideas">Post an idea</Button></div></section>
    <section className="section" id="discover"><div className="section-heading"><div><h2>Recommended for you</h2><p>Projects selected around your skills and interests.</p></div><Link href="#" className="text-link">See all →</Link></div><div className="project-grid">{projects.map((project) => <article className="project-card" key={project.title}><div className="project-top"><span className="project-kicker">PROJECT</span><strong>{project.match}</strong></div><h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.tags.split(" · ").map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><div className="project-divider" /><div className="project-meta"><div><span>Looking for</span><strong>{project.roles}</strong></div><div><span>Squad</span><strong>{project.members}</strong></div></div><Button variant="secondary" className="button-full">View project</Button></article>)}</div></section>
    <section className="dashboard-grid"><article className="panel" id="applications"><div className="section-heading"><div><h2>Your applications</h2><p>Keep an eye on requests you have sent.</p></div></div><div className="stat-row"><div><strong>2</strong><span>Pending</span></div><div><strong>1</strong><span>Accepted</span></div><div><strong>0</strong><span>Rejected</span></div></div><div className="activity-item"><span className="status-dot pending" /><div><strong>AI Healthcare Assistant</strong><small>Application pending review</small></div><span className="muted-small">2h</span></div></article>
    <article className="panel" id="squads"><div className="section-heading"><div><h2>Your squad</h2><p>One active collaboration.</p></div></div><div className="squad-preview"><div className="squad-icon">ST</div><div><strong>Smart Traffic Management</strong><span>3 / 5 members</span></div><span className="progress-mini"><i /></span></div><div className="role-list"><span><b>✓</b> Backend</span><span><b>✓</b> UI/UX</span><span><b>○</b> AI / ML</span><span><b>○</b> IoT</span></div><Button variant="secondary" className="button-full">Open squad</Button></article></section>
    <section className="panel idea-panel" id="ideas"><div><p className="eyebrow">Have an idea?</p><h2>Turn it into a squad.</h2><p>Describe the problem. Squad Sync can help identify the roles and people you need.</p></div><Button href="/app/ideas/new">Create an idea <span aria-hidden="true">→</span></Button></section>
  </div></AppShell>;
}
